export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_USER = "SET_USER";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const MESSAGE_SUCCESS = "MESSAGE_SUCCESS";
export const MESSAGE_ERROR = "MESSAGE_ERROR";

export const BOARD_CREATED = "BOARD_CREATED";
export const FIRST_ITEM_SELECTED = "FIRST_ITEM_SELECTED";
export const SECOND_ITEM_SELECTED = "SECOND_ITEM_SELECTED";
export const CLEAR_SELECTION = "CLEAR_SELECTION";
export const ADD_SCORE = "ADD_SCORE";
export const CLEAR_CURRENT = "CLEAR_CURRENT";
export const SET_GAMES = "SET_GAMES";
export const FINISH_GAME = "FINISH_GAME";
